In [3]:
import pandas as pd
import sqlite3

# --------------------------------------------------
# 1. IMPORT DATA FROM CSV
# --------------------------------------------------

df_csv = pd.read_csv("/content/test_Y3wMUE5_7gLdaTN.csv")

print("CSV DATA:")
display(df_csv.head())


# --------------------------------------------------
# 2. IMPORT DATA FROM EXCEL
# --------------------------------------------------

df_excel = pd.read_excel(
    "/content/Historicalinvesttemp.xlsx",
    sheet_name="Sheet1"
)

print("EXCEL DATA:")
display(df_excel.head())


# --------------------------------------------------
# 3. IMPORT DATA FROM SQL DATABASE
# --------------------------------------------------

# Create a temporary SQLite database
connection = sqlite3.connect("sample.db")

# Store Excel data into SQL table
df_excel.to_sql(
    "data_table",
    connection,
    if_exists="replace",
    index=False
)

# Read data from SQL database
df_sql = pd.read_sql(
    "SELECT * FROM data_table",
    connection
)

print("SQL DATA:")
display(df_sql.head())

connection.close()


# --------------------------------------------------
# 4. IMPORT DATA FROM WEB
# --------------------------------------------------

url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/iris.csv"

df_web = pd.read_csv(url)

print("WEB DATA:")
display(df_web.head())


# --------------------------------------------------
# 5. EXPORT DATAFRAME TO EXCEL
# --------------------------------------------------

output_file = "/content/exported_data.xlsx"

df_csv.to_excel(
    output_file,
    index=False
)

print("DataFrame exported successfully!")
print("File:", output_file)

CSV DATA:

   Student_ID    Name Department  Python  SQL  ML
0         101    Arun       AIML      85   80  88
1         102    Bala        CSE      78   72  75
2         103  Charan       AIML      92   89  94
3         104   Divya        CSE      88   91  85
4         105    Esha        ECE      74   68  70

EXCEL DATA:

   Year  Investment  Temperature  Rainfall  Growth_Rate
0  2015         120         28.4      1120          5.2
1  2016         135         28.7      1085          6.1
2  2017         150         29.1      1195          7.0
3  2018         168         28.9      1030          6.5
4  2019         182         29.3      1275          7.4

SQL DATA:

   Year  Investment  Temperature  Rainfall  Growth_Rate
0  2015         120         28.4      1120          5.2
1  2016         135         28.7      1085          6.1
2  2017         150         29.1      1195          7.0
3  2018         168         28.9      1030          6.5
4  2019         182         29.3      1275          7.4

WEB DATA:

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

DataFrame exported successfully!
File: /content/exported_data.xlsx